" 自动显示高亮，syntastic插件设置
let g:syntastic_check_on_open = 1

" 模糊查找, ctrlp插件
let g:ctrlp_map = ',,'

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'universal-ctags/ctags'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
Plugin 'pearofducks/ansible-vim'
Plugin 'chase/vim-ansible-yaml'
Plugin 'stephpy/vim-yaml'
call vundle#end()  

set ai!
set expandtab  
set mouse=a
set clipboard=unnamed
set nu                       " 设置行号  
set tabstop=4                " 设置tab4个空格  
set shiftwidth=4             " 程序自动缩进时候空格数  
set softtabstop=4            " 退格键一次删除4个空格  
set ignorecase               " 搜索忽略大小写   
set autoindent               " vim使用自动对起，也就是把当前行的对起格式应用到下一行  
set smartindent              " 依据上面的对起格式，智能的选择对起方式，对于类似C语言编写上很有用  
set showcmd                  " 在状态列显示目前所执行的指令  
set hlsearch                 " 开启高亮显示结果
set incsearch                " 开启实时搜索功能
set nowrapscan               " 搜索到文件两端时不重新搜索
set nocompatible             " 关闭兼容模式
set vb t_vb=                 " 关闭提示音
set hidden                   " 允许在有未保存的修改时切换缓冲区
set list                     " 显示Tab符，使用一高亮竖线代替
set listchars=tab:\|\ ,
colorscheme desert           " 设置颜色主题
call pathogen#infect()  
syntax on                    " 语法高亮度显示
filetype indent on           " 针对不同的文件类型采用不同的缩进格式
filetype plugin on           " 针对不同的文件类型加载对应的插件
filetype plugin indent on    " 启用自动补全
autocmd BufNewFile,BufRead *.erb set filetype=html

